### ISSUE TITLE
Failed to sign with Subkey using ChainBridge

### ISSUE THREAD

**Issue by drewstone** [centrifuge/go-substrate-rpc-client#104]
Subkey signing fails when running the chainbridge relayer to sign extrinsics, potentially because we are running a Substrate 2.0 chain. It looks like it fails at signing the extrinsic which goes into this library.

- Any idea how to debug or help if I receive `EROR[10-21|15:50:49] Failed to execute extrinsic              chain=edgeware err="failed to sign with subkey: exit status 1"`?

**Comment by mikiquantum** [comment]
@drewstone The latest release of GSRPC supports Substrate v2.0.0, at least on the template, which is verified by the CI in this project by running tests against: https://github.com/centrifuge/go-substrate-rpc-client/blob/master/docker-compose.yml#L4
That error is most likely due to mismatchin versions of local subkey and the gsrpc lib used.

ChainBridge latest released supports v2.0.0-rc6 and the correspondent subkey-rc6 should be available in the client context.

So for the bridge to work with substrate v2.0.0, will need to update latest gsrpc in that project and compile the correspondent subkey for v2.0.0.
