### ISSUE TITLE
Verification Error: Runtime error: Execution failed: ApiError("Could not convert parameter `tx` between node and runtime: No such variant in enum MultiAddress"

### ISSUE THREAD

**Issue by dcoinapi** [centrifuge/go-substrate-rpc-client#133]
It failed when submit the signed transaction.  But the same code works fine few days ago.

It seems polka update some structure?
https://github.com/polkadot-js/api/commit/b49c2314e782c86fd428d9b5d84a3f77dafced38

**Comment by 1042782229** [comment]
Did you solve this problem? I face too

**Comment by RJman-self** [comment]
I have the same confusion as you

panic: Verification Error: Runtime error: Execution failed: ApiError("Could not convert parameter `tx` between node and runtime: Error decoding field Call :: Multisig.0")

**Comment by litterGuy** [comment]
Verification Error: Runtime error: Execution failed: ApiError(FailedToConvertParameter { function: "validate_transaction", parameter: "tx", error: Error { cause: None, desc: "Could not decode `MultiAddress`, variant doesn\'t exist" } })

**Comment by frankli-dev** [comment]
I have the same issue in the following two cases
- using polkadotjs app connected with the local substrate node
- using go-substrate-rpc-client to send transaction

For the first case, I fixed the issue by adding the following type definition to polkadotjs app (developer settings)
```
{
   "Address": "MultiAddress",
   "LookupSource": "MultiAddress"
}
```
It was `AccountId` instead of `MultiAddress`. After updating it, it works successfully on polkadotjs app.

For the second case, the project (which is using this `go-substrate-rpc-client`) is not written by myself so I'm not sure where I can update the type definitions for serializing.
I'm checking but if anybody can get this as the clue?

**Comment by frankli-dev** [comment]
Ah, I've found the relevant conversation here. https://github.com/centrifuge/go-substrate-rpc-client/pull/128

They are not gonna merging the pull request for now and recommend another rpc client for substrate v3.

https://github.com/Snowfork/go-substrate-rpc-client

**Comment by frankli-dev** [comment]
Oops. It seems the latest message says that the appropriate PR is merged.

https://github.com/centrifuge/go-substrate-rpc-client/pull/143

**Comment by vedhavyas** [comment]
Closing this since the latest master should support the MultiAddress issues with chains using MultiAddres. Do open this if you see any issues

**Comment by frankli-dev** [comment]
> Closing this since the latest master should support the MultiAddress issues with chains using MultiAddres. Do open this if you see any issues
@vedhavyas 
Can we release the latest version as new tag, please?

**Comment by vedhavyas** [comment]
@frankli-dev yeap. Coming soon 👍🏼
