### ISSUE TITLE
support all events which exists in metadata

### ISSUE THREAD

**Issue by mr-tron** [centrifuge/go-substrate-rpc-client#191]
I made generator https://gist.github.com/mr-tron/c8e4640aedd87ba3a2a03ec21b36773a
it's made for previous substrate version (metadata v12) but you can easily modify it for any substrate version and you requirements. It prints to stdout all events types from all modules in format for  file types/events.go and for types/event_record.go:60 EventRecordsRaw

**Comment by vedhavyas** [comment]
Hey @mr-tron 
unfortunately, that doesn't solve the problem. Since each chain will have its own set of events, gsrpc only brings the events from main susbtrate pallets. The remaining events need to be added manually for each project at the moment. Please have look here on how to add events that are missing https://github.com/centrifuge/go-centrifuge/blob/develop/centchain/events.go#L172

**Comment by mr-tron** [comment]
I understand. I just made tool for automatization the process.
And it looks like gsrpc doesn't support all polkadot events (like Staking_Kicked) but I don't sure. My script can help with keeping it uptodate.
