### ISSUE TITLE
ChargeAssetTxPayment extension  hasn't support?

### ISSUE THREAD

**Issue by ParkerXie** [centrifuge/go-substrate-rpc-client#240]
Hi,My blockchain base on substraste  that use pallet ChargeAssetTxPayment ,when I submitextrics with  go-substrate-rpc-client always return following error:
Code:1002
Message:"Verification Error: Runtime error: Execution failed: ApiError(FailedToConvertParameter { function: \"validate_transaction\", parameter: \"tx\", error: Error { cause: Some(Error { cause: None, desc: \"unexpected first byte decoding Option\" }), desc: \"Could not decode `ChargeAssetTxPayment::asset_id`\" } })"

how should I do  to resolve this problem

**Comment by mikiquantum** [comment]
Hi @ParkerXie,

We haven't added support for `ChargeAssetTxPayment` type, so you would need to create your own encoder/decoder based on the assetId type that is passed from the runtime. Making sure that the when encoding the struct you prepend 1 to the rest of the value or 0 if none, since that value is an Option and it always expects Some or None.

**Comment by puneetjindal3** [comment]
@ParkerXie I'm also facing the same issue. did you find anything for that?

**Comment by puneetjindal3** [comment]
@mikiquantum Can you just explain it more?

**Comment by mohaijiang** [comment]
I got same issue.

**Comment by cdamian** [comment]
Please try https://github.com/centrifuge/go-substrate-rpc-client/tree/add-charge-asset-tx-support.

**Comment by ParkerXie** [comment]
> Please try https://github.com/centrifuge/go-substrate-rpc-client/tree/add-charge-asset-tx-support.

This worked for me, thank you!
