### ISSUE TITLE
Request for DeepBrain integration in go-substrate-rpc-client

### ISSUE THREAD

**Issue by yaoyf888** [centrifuge/go-substrate-rpc-client#369]
I would like to request the integration of DeepBrain as a supported chain in the go-substrate-rpc-client SDK. Currently, I am facing issues when working with this SDK as it is unable to parse many transaction events. As a result, our program gets stuck and we are unable to extract important transaction data for our users.

DeepBrain integration would greatly benefit users like us who rely on the go-substrate-rpc-client SDK for interacting with Substrate-based networks. With DeepBrain support, we would be able to seamlessly handle transaction events and ensure a smooth data extraction process.

I kindly request the go-substrate-rpc-client team to consider adding support for DeepBrain, which would enhance the overall functionality and usability of the SDK.

Thank you for your attention to this matter.

**Comment by cdamian** [comment]
Hi @yaoyf888.

Please refer to the comment I made here - https://github.com/centrifuge/go-substrate-rpc-client/issues/357#issuecomment-1840748032

Unfortunately, we cannot add any event types that are specific to your chain since that would also mean that we would have to maintain those as well, to some degree, and that is not feasible. For example, we also have our own repository with the types needed for events/calls - https://github.com/centrifuge/chain-custom-types, and every time there is a change, we update that repo accordingly, we suggest you do something similar and/or check the initial suggestion related to event parsing.
