### ISSUE TITLE
blake2b 

### ISSUE THREAD

**Issue by tdmm** [centrifuge/go-substrate-rpc-client#57]
this code :
func Test_SS58(t *testing.T) {
//seed := 0xdba9807c8606e46341dcac32dbf1c9ec25dae6a3bc386d83d8bde4d6ab72408e
	publicKey := "aa29cb6398bc70bfedbd4f7af69dd4c24b2d0b07ebb962699954c0e06d99112e"
	addr := "5FupQuyf8STcPCf3DfUPxhNWunxi8R4PiydFwUywdZiRE3cz"

	pub, err := hex.DecodeString(publicKey)
	if err != nil {
		panic(err)
	}

	checkSum := blake2b.Sum256(pub)
	d := base58.Decode(addr)

	fmt.Printf("d:%0x \n checksum:%0x", d, checkSum)
}

and the result is :
d:2aaa29cb6398bc70bfedbd4f7af69dd4c24b2d0b07ebb962699954c0e06d99112eaa97 
 checksum:c61d902e300e32c48fee79518f750976e8570df9faece77dc80f5271c2625e16 

the decode of addr checksum is "aa97",not euqal the checksum.
what's wrong?

**Comment by philipstanislaus** [comment]
If I understand correctly what you want to do (verifying the checksum of a public key against the address), then you should hash not just the pub key, but also the SS58 address type, as explained here: https://github.com/paritytech/substrate/wiki/External-Address-Format-(SS58)#checksum-types

I'm closing this issue since I believe it's not directly a problem with go-substrate-rpc-client. Please reply here if I misunderstood you. Thanks!
